### ISSUE TITLE
npm ERR! addLocal Could not install ../drator

### ISSUE THREAD

**Issue by ooip** [ryardley/reduxor#5]
Hi,

I cloned the repo, tried `npm i` and got an `ENOENT` error.
`npm ERR! enoent ENOENT, open '/Users/me/redux-tut/drator'`

I checked the `package.json` file, and found `"drator": "../drator"`as dependency. Do I need to install `drator`?

**Comment by ryardley** [comment]
Thanks for pointing this out. My bad! Fixed.
